### PR TITLE
Update to use react-leaflet 4.1.0, the newest version as of this writing.

### LINKED ISSUE #2: Update to react-leaflet 4.0.0+
`MapConsumer` was [removed in react-leaflet 4.0.0](https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v400-2022-04-18), so that your example works in react-leaflet 3.x but not 4.x.

I found this example enormously helpful, and I'm sure others have and will in the future.  If you like, I can submit a PR updating your starter kit.

### PR DESCRIPTION
**Pull request by theGOTOguy**
Also updates other dependencies.

The only code change involves removing `MapConsumer`, which is no longer part of the react-leaflet API.

Resolves #2.

### CODE REVIEW

**Comment by theGOTOguy** [comment]
@colbyfayock It looks to me like the checks are failing in netlify because the node version is set to 12, where it should be at least 14 to be compatible with the updated packages.  In fact, it should be safe to update node to the newest LTS support, 18.

**Comment by colbyfayock** [comment]
i can't figure out how to upgrade to a later version of node without adding a change. not seeing an env var and currently dont have an .nvmrc

can you do me a favor and push a new file `.nvmrc` file in the root with 18?

**Comment by theGOTOguy** [comment]
Adding `.nvmrc` got it, and I manually tested that it works as expected.  You should be good to go now!

**Comment by colbyfayock** [comment]
before i merge this in - the repository wasn't set up for hacktoberfest. i just added the topic, but im not sure if your existing PR would qualify? if you'd like, you could close this and repoen the same code to get credit, up to you. if i dont hear from you by tomorrow afternoon ill go ahead and merge

thanks

**Comment by theGOTOguy** [comment]
You can go ahead and merge.  I'm just happy to leave things a little better for anyone who follows.
 
Thanks for providing this resource!

**Comment by colbyfayock** [comment]
awesome thank you!

**Comment by colbyfayock** [comment]
@all-contributors please add @theGOTOguy for code

**Comment by colbyfayock** [comment]
even though the PR didn't count for the official hacktoberfest, i'd be happy to send you some swag as part of my hacktoberfest special :)

https://spacejelly.dev/hacktoberfest/

send me an email at hello@colbyfayock.com where i'll send you a form to claim your swag

**Pull request merged**
